apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-vta-microfrontend
  namespace: paw
  labels:
    team: paw
spec:
  envFrom:
    - secret: tms-vta-microfrontend-secrets
  image: { { version } }
  port: 7100
  liveness:
    path: /tms-vta-microfrontend/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-vta-microfrontend/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-vta-microfrontend/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://person.dev.nav.no/tms-vta-microfrontend"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi
